services:
  api:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGO_DB_NAME=Clinica
      - JWT_SECRET_KEY=misuperclavedeldestinofinal
    depends_on:
      - mongodb
    networks:
      - api-citas-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - api-citas-network

  nginx:
    image: nginx:latest
    ports:
      - "5001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - api-citas-network

networks:
  api-citas-network:
    driver: bridge

volumes:
  mongo-data:
